import type { Lang } from "./lang";

export type ProductCopy = {
  title: string;
  essence: string;
  who: string;
  gets: string;
  how: string;
  why: string;
  next: string;
};

export type Product = {
  slug: string;
  group: string;
  site: "irina" | "bureau";
  image: string;
  demo?: boolean;
  ru: ProductCopy;
  en: ProductCopy;
};

function P(
  slug: string,
  group: string,
  site: Product["site"],
  image: string,
  ru: ProductCopy,
  en: ProductCopy,
  demo = false,
): Product {
  return { slug, group, site, image, ru, en, demo };
}

export const irinaProducts: Product[] = [
  P("master-plan", "vladimir", "irina", "/images/territory.jpg", {
    title: "Мастер-план раскрытия потенциала территории",
    essence: "Фундаментальная работа с историей, культурой, ландшафтом и тем, что здесь реально возможно. Показываю не только допустимое по бумагам, а то, что будет сильным и уместным именно на этом месте.",
    who: "Для собственников, администраций и инвесторов, у которых есть земля и вопрос, что с ней делать дальше. Особенно когда участок сложный: наследие, рельеф, ограничения, ожидания города.",
    gets: "Основание для решений, с которым можно идти к инвесторам, в администрацию и к проектировщикам. Ясность: что усиливать, что не трогать, куда смотреть в первую очередь.",
    how: "Собираю историю места, культурный слой, ландшафт и реальные возможности. Сверяю гипотезы с тем, что территория выдержит. Фиксирую выводы так, чтобы ими можно было пользоваться сразу.",
    why: "Формально допустимое и по-настоящему сильное — разные вещи. Хороший мастер-план экономит годы споров, потому что заранее отделяет уместное от случайного.",
    next: "Результат — мастер-план с логикой развития и понятными следующими шагами. После него обычно переходят к концепции, АГО или разговору с инвесторами.",
  }, {
    title: "Master plan for a territory’s potential",
    essence: "A deep reading of history, culture, landscape and what is actually possible here — not only what the papers allow.",
    who: "Owners, municipalities and investors with land and an open question. Especially on difficult sites: heritage, relief, constraints, civic expectation.",
    gets: "A basis for decisions that can go to investors, the city and the design team. What to strengthen, what to leave, where to look first.",
    how: "I gather the place’s history, cultural layer, landscape and real capacity. Hypotheses are checked against what the land will bear.",
    why: "Legal and strong are not the same. A good master plan saves years of argument.",
    next: "A master plan with a development logic and next steps. Then concept, appearance pack, or a talk with investors.",
  }),
  P("concept", "vladimir", "irina", "/images/territory.jpg", {
    title: "Идеологическое и концептуальное проектирование",
    essence: "Сборка смысловой платформы объекта. Соединяю идеологию, архитектуру и экономику в одно решение, выдержанное по смыслу, контексту и реализуемости.",
    who: "Для тех, у кого есть задача или участок, но ещё нет точной идеи, зачем этот объект здесь. Особенно когда «просто красиво» недостаточно.",
    gets: "Связную идеологическую платформу, а не набор картинок. Формулировку, с которой можно идти в АГО, к инвесторам и дальше в проектирование.",
    how: "Формулирую идеологию объекта и связываю её с архитектурой и экономикой. Опираюсь на работу лаборатории «Владимир». Проверяю, выдерживает ли идея контекст и реализацию.",
    why: "Поверхностная идея рассыпается на согласованиях и в смете. Глубокая концепция экономит дальнейшую работу: все решения растут из одной платформы.",
    next: "Концептуальный документ с идеологией, образом и логикой развития. Затем АГО, объёмно-планировочные решения или мастер-план.",
  }, {
    title: "Ideology and concept",
    essence: "A meaning platform for the object: ideology, architecture and economy as one holdable idea.",
    who: "When there is a brief or a site, but not yet a reason for this object to exist here.",
    gets: "A connected platform, not a set of pictures. Something that can go to appearance review, investors and design.",
    how: "I state the ideology and bind it to architecture and money. The Vladimir laboratory gives the research base.",
    why: "A thin idea fails at committee and in the cost plan. A deep one saves the work that follows.",
    next: "A concept document. Then appearance pack, spatial plan or master plan.",
  }),
  P("ago", "vladimir", "irina", "/images/mansion.jpg", {
    title: "Архитектурно-градостроительный облик",
    essence: "Комплект, который показывает внешний вид объекта в логике конкретной территории и градсовета. Обликом можно выходить на согласование и защищать решение — не только «понравиться комиссии».",
    who: "Для проектов, где внешний вид проходит градсовет или иные инстанции. Особенно в зонах с особыми требованиями к облику.",
    gets: "Материалы под стандарты конкретного градсовета. Документ, с которым реально идти на согласование: облик вырастает из идеологии и контекста места.",
    how: "Изучаю требования территории и логику того градсовета, куда предстоит выходить. Собираю облик из уже найденной концепции. Готовлю комплект в рабочем, а не декоративном виде.",
    why: "АГО часто становится точкой, где проект либо спокойно двигается, либо надолго застревает.",
    next: "Комплект АГО в требуемом формате. После согласования — стадия П или объёмно-планировочные решения.",
  }, {
    title: "Urban appearance pack (AGO)",
    essence: "The look of the building in the logic of this territory and this planning board — a pack you can defend, not only display.",
    who: "Projects that must pass a planning board, especially in regulated appearance zones.",
    gets: "Materials in the standard of that board. Appearance grown from ideology and place.",
    how: "I read the territory and the board. The pack is built from the concept, in working form.",
    why: "AGO is often where a project either moves or stalls for months.",
    next: "The pack in the required format. Then stage P or spatial design.",
  }),
  P("research", "vladimir", "irina", "/images/lab.jpg", {
    title: "Исследования: исторические, культурные, технологические",
    essence: "Не архивная справка, а рабочая матрица: история, право, архитектура и технология собираются в одно основание для решений.",
    who: "Для объектов с историческим, культурным или конструктивным слоем — когда двигаться «на глаз» слишком рискованно.",
    gets: "Сводку, которой можно пользоваться. Связанную картину: что объект собой представляет, какие ограничения жёсткие, какие преодолимые.",
    how: "Собираю историю, право, архитектуру и технологию в одну матрицу. Проверяю, какие выводы следуют для концепции, облика и согласований.",
    why: "Без сводки дальше работают вслепую: концепция не стыкуется с наследием, АГО не проходит, адаптация начинается заново.",
    next: "Исследовательский отчёт как рабочая матрица и выводы. Затем концепция, АГО, согласования или адаптация.",
  }, {
    title: "Historical, cultural and technical research",
    essence: "Not an archive note — a working matrix of history, law, architecture and technology.",
    who: "Objects with a heritage or structural layer, when working by eye is too risky.",
    gets: "A usable synthesis: what the object is, which limits are hard, which are workable.",
    how: "History, law, architecture and technology in one matrix, aimed at concept, appearance and approvals.",
    why: "Without it, concept, AGO and adaptation start blind.",
    next: "A research report. Then concept, AGO, approvals or adaptation.",
  }),
  P("consulting", "vladimir", "irina", "/images/territory.jpg", {
    title: "Консалтинг",
    essence: "Можно консультироваться, не запуская сразу проектирование. Я сама предлагаю этот шаг: быстро разобраться, что делать сейчас, и наметить путь.",
    who: "Для тех, кому нужен целостный взгляд — от смысла и архитектуры до экономики, согласований и жизни объекта после реализации.",
    gets: "Рекомендации из исследования и практики, а не из общих схем. Понимание следующего шага без обязательства сразу заказывать проект.",
    how: "Смотрю задачу целиком. Опираюсь на реализованные проекты и местный контекст. Предлагаю консультацию как первый шаг сотрудничества.",
    why: "Открытость и скорость: это лучший путь быстро понять, что действительно нужно делать сейчас.",
    next: "Встреча или дистанционный разбор. Дальше — аудит, адаптация, согласования или концепция.",
  }, {
    title: "Consulting",
    essence: "Advice without launching a full design. I offer this as the first step: what to do now, and which path.",
    who: "Anyone who needs a whole view — from meaning and architecture to money, approvals and life after opening.",
    gets: "Recommendations from research and built work, not generic schemes. A next step without a forced contract.",
    how: "I look at the task as a whole and start with a consultation.",
    why: "Openness and speed: the fastest way to see what is actually needed.",
    next: "A meeting. Then audit, adaptation, approvals or concept.",
  }),
  P("audit", "vladimir", "irina", "/images/territory.jpg", {
    title: "Контекстный аудит проекта",
    essence: "Спокойная оценка, где проект может столкнуться с проблемами, а где есть пространство для сильного решения. Глубину выбираете вы.",
    who: "Для тех, у кого уже есть идея, участок или материалы — и хочется понять положение дел, не запуская тяжёлую проектную машину.",
    gets: "Картину рисков и возможностей. Что делать сейчас, а что можно отложить. Выводы без обязательства сразу заказывать проектирование.",
    how: "Смотрю задачу в том объёме, который нужен на этом этапе. Разбираю контекст, ограничения и развилки.",
    why: "Большинство дорогих ошибок рождаются не на чертежах, а в слепой уверенности, что «и так понятно».",
    next: "Аудит выбранной глубины. Затем адаптация, согласования или концепция.",
  }, {
    title: "Contextual project audit",
    essence: "A calm reading of where the project may fail and where a strong move is still open. You choose the depth.",
    who: "When an idea, a site or a pack already exists and you want the real picture without a full design machine.",
    gets: "Risks and openings. What to do now. No forced next contract.",
    how: "I look only as deep as this stage needs.",
    why: "Expensive errors start in the belief that it is already obvious.",
    next: "An audit. Then adaptation, approvals or concept.",
  }),
  P("adaptation", "vladimir", "irina", "/images/mansion.jpg", {
    title: "Адаптация проекта",
    essence: "Привести уже существующие материалы к рабочему стандарту. Аудит внутри — без отдельной доплаты и без работы вслепую.",
    who: "Когда проект уже есть, но его нельзя защищать, согласовывать или строить в текущем виде.",
    gets: "Чёткий комплект по стандарту: альбом АГО, рабочая документация и другие необходимые материалы, а не размытые рекомендации.",
    how: "Сначала аудирую то, что есть. Собираю недостающее. Привожу документацию к нужному стандарту.",
    why: "Адаптировать дешевле, чем рисовать заново — если делать это не вслепую.",
    next: "Комплект документов. Затем согласование, доработка разделов или сопровождение инстанций.",
  }, {
    title: "Project adaptation",
    essence: "Bring existing materials to a working standard. Audit is included — not billed as a separate blind pass.",
    who: "When a project exists but cannot yet be defended, approved or built.",
    gets: "A clear pack: appearance album, working drawings and whatever else the standard needs.",
    how: "I audit what exists, fill the gaps, bring the documents to standard.",
    why: "Adaptation is cheaper than drawing again — if it is not done blind.",
    next: "A document pack. Then approvals or further design.",
  }),
  P("approvals", "vladimir", "irina", "/images/territory.jpg", {
    title: "Согласования и экспертизы",
    essence: "Разбор ситуации, реалистичная стратегия прохождения и ведение процесса до результата. Если берёмся — не оставляем заказчика один на один с инстанциями.",
    who: "Для проектов, которым предстоит градсовет, экспертиза или другие согласования. Особенно когда сроки жёсткие или история уже сложная.",
    gets: "Быструю оценку шансов и понятную стратегию. Если идём в сопровождение — ведение до результата.",
    how: "Оперативно разбираю исходные данные и требования инстанции. Предлагаю маршрут. Если берёмся — доводим до результата.",
    why: "Согласования редко проигрываются «в целом» — чаще на деталях, сроках и неверной стратегии.",
    next: "Сначала оценка шансов. Затем, если стороны готовы, сопровождение до результата.",
  }, {
    title: "Approvals and expert review",
    essence: "A realistic path through boards and review. If we take it, we do not leave you alone with the authorities.",
    who: "Projects facing a planning board, expert review or other consents — especially with tight time or a difficult history.",
    gets: "A fast reading of chances and a strategy. If we accompany — we stay until the result.",
    how: "I read the data and the authority. Then a route. Then, if taken, delivery.",
    why: "Approvals are rarely lost “in general”. They are lost on detail, time and a wrong strategy.",
    next: "First the chances. Then accompaniment if both sides agree.",
  }),
  P("vision", "hospitality", "irina", "/images/resort.jpg", {
    title: "Визионерская концепция туристического комплекса",
    essence: "Экспресс-формат, часто за чашку кофе. Показываю, какой объект сделала бы здесь сама: не универсальный вариант «для рынка», а свой взгляд на этот участок.",
    who: "Для тех, у кого есть земля или идея комплекса, и хочется быстро понять, по пути ли нам.",
    gets: "После встречи — pack: майндмэп по идеологии, продуктовая матрица и экспресс-финмодель. Материал остаётся у вас.",
    how: "За одну встречу смотрю участок и задачу. Показываю, какой объект вижу. Собираю соображения с проверкой, сможет ли идея зарабатывать.",
    why: "Это не продажа полного проекта, а быстрая проверка совместимости. Низкий порог входа.",
    next: "Встреча. На выходе — pack идей. Если совпали — сессия или мастер-план живого объекта.",
  }, {
    title: "Vision concept for a tourist complex",
    essence: "A short format, often over coffee. What I would make here — not a generic market option.",
    who: "Land or an idea, and a need to know quickly if we are on the same path.",
    gets: "A pack: ideology map, product matrix, a first financial sketch. It stays with you.",
    how: "One meeting. The site, the task, the object I see, and whether it can earn.",
    why: "Not a full-project sale. A low-threshold test of fit.",
    next: "A meeting and a pack. Then a session or a living master plan.",
  }),
  P("tourism-plan", "hospitality", "irina", "/images/resort.jpg", {
    title: "Мастер-план живого туристического объекта",
    essence: "Связывает территорию, экономику, архитектуру и стратегию в один документ. Внутри сразу задаю архитектурный характер.",
    who: "Для тех, кто понял, что объект может жить, и готов собирать его как систему, а не как красивый генплан отдельно от бизнеса.",
    gets: "Рабочий пакет: зонирование, состав и ёмкость, сценарии гостя, очереди реализации. Документ, по которому можно проектировать и считать деньги.",
    how: "Четыре слоя в одном плане. Жизнь комплекса через путь гостя. Одновременно — архитектурный характер объекта.",
    why: "Отдельно картинка участка и отдельно бизнес потом не сходятся.",
    next: "Мастер-план как рабочий пакет. Затем проектирование очередей, сопровождение или финансовая модель.",
  }, {
    title: "Master plan of a living tourist place",
    essence: "Territory, economy, architecture and strategy in one document — with character from the first sheet.",
    who: "When the place can live, and you are ready to assemble a system, not a pretty plan beside a business idea.",
    gets: "A working pack: zoning, capacity, guest scenarios, phases. Something to design and to count from.",
    how: "Four layers. The guest’s path. The architectural character at the same time.",
    why: "A picture of the land and a business, kept apart, do not meet later.",
    next: "The pack. Then phased design, accompaniment or a financial model.",
  }),
  P("session", "hospitality", "irina", "/images/lodge.jpg", {
    title: "Стратегическая сессия «Проект, который живёт»",
    essence: "Один день совместной работы: собираем архитектуру и бизнес-модель и проверяем, будет ли объект жить.",
    who: "Для инвестора или собственника, который за один день хочет понять: идём дальше, меняем гипотезу или не берёмся.",
    gets: "К концу дня — ясность. Совместно собранные архитектура и модель, а не презентация «с картины».",
    how: "Интенсив. Вместе собираем образ, логику гостя и модель. К вечеру фиксируем развилку.",
    why: "Готовая концепция «под ключ» часто не приживается, потому что в ней нет заказчика.",
    next: "Один рабочий день. Затем мастер-план или комплексное сопровождение.",
  }, {
    title: "Strategy session: a project that lives",
    essence: "One day: architecture and business model together, tested for life.",
    who: "An owner who wants, in a day, to go on, change the hypothesis, or stop.",
    gets: "Clarity by evening. A joint decision, not a slide deck from a picture.",
    how: "An intensive. Image, guest logic, model. Then the fork.",
    why: "A turnkey concept often fails because the client is not in it.",
    next: "One working day. Then a master plan or full accompaniment.",
  }),
  P("hospitality-lead", "hospitality", "irina", "/images/lodge.jpg", {
    title: "Комплексное сопровождение проекта",
    essence: "Ведение туристического объекта от замысла до ключевых решений на реализации. На площадке берегу смысл, характер и опыт гостя, а не только соответствие чертежам.",
    who: "Для тех, кто не хочет, чтобы замысел растерялся между проектировщиками, подрядчиками и стройкой.",
    gets: "Сквозное авторское ведение. Присутствие на развилках. Защиту впечатления гостя и характера места.",
    how: "Веду проект от концепции до площадки. На ключевых развилках подключаюсь сама.",
    why: "Даже сильный мастер-план может потеряться на стройке в мелочах.",
    next: "Формат зависит от этапа. Обычно начинается после мастер-плана или сессии.",
  }, {
    title: "Full project accompaniment",
    essence: "Leading a tourist object from idea to key decisions on site. I guard meaning and guest experience, not only drawings.",
    who: "When the idea must not be lost between designers, contractors and the site.",
    gets: "Authorship through the chain. Presence at forks. Protection of the guest’s impression.",
    how: "From concept to the ground. I join the decisive turns myself.",
    why: "A strong master plan can still die in small site decisions.",
    next: "The format follows the stage. Usually after a master plan or session.",
  }),
  P("estate-analysis", "houses", "irina", "/images/house.jpg", {
    title: "Предпроектный анализ частных владений",
    essence: "Знакомство с будущим проектом, аудит ситуации и первичный синтез решения. Ищу предпосылки и барьеры, вижу возможности и риски. Смотрю широко и ухожу вглубь ровно настолько, чтобы не проектировать вслепую.",
    who: "Для тех, у кого есть участок или идея, но ещё нет ясности, с чего начинать. Особенно когда территория нетипичная или видение будущего размыто.",
    gets: "Картину по нескольким разрезам сразу: архитектура, рельеф и геология, правила, экономика, то, как вы будете здесь жить. Не список ограничений, а понимание, что усиливать и с чем лучше не спорить.",
    how: "Сначала беру ширину — разные слои рядом. Потом глубину: до инженерных анализов и до прошлого не только места, но и вашего — чтобы соединить участок и будущую жизнь, а не подогнать одно под другое.",
    why: "Лишнее в частном доме появляется рано, часто ещё до проекта, из уверенности, что «и так понятно», или из принципа «все так делают». Честный разбор экономит бюджет на следующих стадиях.",
    next: "Результат — эскиз видения: выводы и рекомендации. Дальше обычно концептуальное проектирование.",
  }, {
    title: "Pre-design analysis of a private estate",
    essence: "A first reading of the future house: audit of the situation and a first synthesis. I look as wide and as deep as needed so we do not design blind.",
    who: "When there is land or an idea, but not yet a start. Especially on an unusual site, or when the future is still vague.",
    gets: "Several cuts at once: architecture, relief and geology, rules, economy, how you will live here. Not a list of limits — what to strengthen and what not to fight.",
    how: "Width first, then depth: to engineering, and to the past of the place and of you — so land and life meet, instead of one being forced onto the other.",
    why: "Waste in a private house starts early, often before design, from “it is obvious” or “everyone does it this way”.",
    next: "A sketch of vision: findings and advice. Then usually concept design.",
  }),
  P("estate-plan", "houses", "irina", "/images/house.jpg", {
    title: "Мастер-планирование частных владений",
    essence: "Собирает дом и территорию в одно целое — до того, как проект разъедется по разделам. Работаю своим методом и говорю с вами напрямую.",
    who: "Семьи и собственники частных территорий, которым нужен дом, живущий в ландшафте, а не универсальный объект «на показ».",
    gets: "Рабочий план, которым можно пользоваться, а не набор разрозненных мыслей и схем. Характер именно ваш.",
    how: "Смотрю участок исследовательски. Личное общение без ассистентов. Делаем то, что будет красиво именно для вас, а не вообще.",
    why: "Если дом и земля не собраны в одно целое в начале, дальше они живут разными жизнями — и дорого сходятся.",
    next: "Рабочий мастер-план. Затем концепция, АГО или ТЗ.",
  }, {
    title: "Master planning of private estates",
    essence: "House and ground as one whole — before the project splits into folders. My method, and I speak with you directly.",
    who: "Families who need a house that lives in the land, not a generic display object.",
    gets: "A working plan, not loose thoughts and diagrams. Character that is yours.",
    how: "I read the site as research. No assistants in between. Beauty for you, not in general.",
    why: "If house and land are not one from the start, they live apart — and meet expensively later.",
    next: "A working master plan. Then concept, appearance pack or brief.",
  }),
  P("estate-concept", "houses", "irina", "/images/house.jpg", {
    title: "Идеологическое и концептуальное проектирование частных владений",
    essence: "Сборка образа и логики жизни на участке. Беру её только после предпроектного анализа: быстрее и точнее, без красивых гипотез «с нуля».",
    who: "Для тех, кто хочет дом с тихой, не кричащей эстетикой — авторской, но вписанной в вас и в место. Подходит и когда в программе не только семья: хозяйство, мастерская, гости или ферма.",
    gets: "Образ, описание, комплект: культура, техника, технологии, стиль, обеспечение и правовая рамка. Уже на эскизах — бюджет и ТЭО. Понятно, как здесь будут жить люди и течь процессы.",
    how: "Держу позицию генпроектировщика: блоки собираются вместе. Параллельно считаю деньги на эскизах и разбираю редкие узлы — то, что обычно оставляют «на потом».",
    why: "Идея без анализа и без счёта быстро ломается на стройке. Здесь характер, быт и бюджет идут рядом.",
    next: "Концепция с идеологией, образом, логикой жизни и ранним ТЭО. Затем АГО, ТЗ или стадия проектирования.",
  }, {
    title: "Ideology and concept of a private estate",
    essence: "Image and the logic of life on the land. Taken only after pre-design analysis — faster, more precise, no pretty hypotheses from nothing.",
    who: "Anyone who wants a quiet, unshouting aesthetic — authored, but fitted to you and the place. Also when the brief is more than a family: workshop, guests, a farm.",
    gets: "Image, description, a pack of culture, technique, style, supply and law. Budget and feasibility already at sketch. How people will live and how processes will run.",
    how: "I hold the lead designer’s seat: blocks come together. Money is counted on the sketches; rare junctions are solved now, not later.",
    why: "An idea without analysis and without a count breaks on site. Character, daily life and budget travel together.",
    next: "A concept with ideology, image, life-logic and an early feasibility. Then appearance pack, brief or design stage.",
  }),
  P("estate-ago", "houses", "irina", "/images/house.jpg", {
    title: "Архитектурно-градостроительный облик частных владений",
    essence: "Показывает, как дом выглядит в своём месте. Работаю со всеми слоями сразу: ландшафт, код территории, ваша история — чтобы дом спокойно встал в среду или уверенно стал её акцентом.",
    who: "Когда внешний вид идёт на согласование или когда важно не спорить с окружением. И когда хочется сознательно выбрать: раствориться в участке или держать характер.",
    gets: "Комплект облика с понятным основанием: почему именно так, а не «потому что красиво». История места и ваша легенда читаются в фасадах и в посадке на рельеф.",
    how: "Смотрю рельеф и окружение. Сверяюсь с кодом территории. Собираю смысл — зачем дом появляется именно здесь — и перевожу его во внешний вид.",
    why: "Случайный фасад на частном участке быстро выглядит чужим. Когда облик вырастает из места и из вас, согласования проще, а жить с ним спокойнее.",
    next: "Комплект АГО. Затем ТЗ, стадия П или уточнение концепции.",
  }, {
    title: "Urban appearance pack for a private house",
    essence: "How the house looks in its place. Landscape, territorial code and your history at once — so the house settles into the ground or holds it as an accent.",
    who: "When the look goes to approval, or when you do not want to argue with the surroundings. And when you choose: dissolve into the plot, or keep character.",
    gets: "An appearance pack with a reason: why this, not “because it is pretty”. The place’s history and your legend in the facades and in the sit on the relief.",
    how: "Relief and neighbours. The code of the territory. Why the house appears here — then that meaning into the look.",
    why: "A casual facade on private land quickly looks foreign. Grown from place and from you, it passes more calmly, and is easier to live with.",
    next: "The appearance pack. Then brief, stage P, or a sharper concept.",
  }),
  P("estate-brief", "houses", "irina", "/images/house.jpg", {
    title: "ТЗ на проектирование частного дома",
    essence: "Документ, который фиксирует рамки до тяжёлой стадии. Опираюсь на опыт управления бюро больше десяти лет и на реальный порядок стройки, а не на голую теорию.",
    who: "Для тех, кто уже понял задачу и готов закрепить договорённости. Особенно когда сторон несколько и потом легко услышать: «мы имели в виду другое».",
    gets: "Рабочее задание: им можно пользоваться как договором смыслов и как чек-листом следующих шагов. Понятно вам, проектировщикам и всем, кому есть дело до дома.",
    how: "Собираю требования так, как бюро реально ведёт проекты и как идут строительные процессы. Пишу не «для папки», а чтобы по тексту можно было двигаться без бесконечных уточнений.",
    why: "Слабое задание размножает переделки. Сильное экономит время на следующих стадиях и держит общий язык.",
    next: "Согласованное ТЗ. Затем стадия П или рабочая документация.",
  }, {
    title: "Design brief for a private house",
    essence: "The document that sets the frame before the heavy stage. Drawn from more than ten years of running a bureau, and from how building actually proceeds — not from theory.",
    who: "When the task is clear and agreements must be fixed. Especially when there are several parties, and “we meant something else” comes easily later.",
    gets: "A working brief: a contract of meanings and a checklist of next steps. Clear to you, to designers, to anyone with a stake in the house.",
    how: "I gather requirements the way the bureau actually runs projects and the way the site actually moves. Not for a folder — so the text can be used without endless clarifications.",
    why: "A weak brief multiplies remakes. A strong one saves the next stages and keeps a common language.",
    next: "An agreed brief. Then stage P or working drawings.",
  }),
  P("estate-lead", "houses", "irina", "/images/house.jpg", {
    title: "Сопровождение реализации частного дома",
    essence: "Ведение стройки силами бюро, а не передача чертежей «и удачи». В работу входит команда, а не один взгляд с расстояния.",
    who: "Заказчики, которые уже выбрали направление дома и не хотят остаться один на один со стройкой.",
    gets: "Исполнителей из проверенного круга мастеров. Сложные места собираем вместе с производителями, а не только с подрядчиком.",
    how: "Подключаю бюро на нужной стадии. Держу прямой разговор между вами, проектом и теми, кто строит.",
    why: "Частный объект особенно раним к человеческому фактору на площадке. Комфорт сегодня и запас на завтра.",
    next: "Формат зависит от этапа. Обычно до ключевых решений реализации и ввода.",
  }, {
    title: "Delivery of a private house",
    essence: "The bureau on the site — not drawings handed over with “good luck”. A team, not one glance from a distance.",
    who: "Clients who have chosen a direction and do not want to face the site alone.",
    gets: "Makers from a proven circle. Difficult places assembled with manufacturers, not only with the contractor.",
    how: "The bureau joins at the stage that is needed. A direct talk between you, the project and those who build.",
    why: "A private house is exposed to chance on the ground. Comfort now, and a reserve for later years.",
    next: "The format follows the stage. Usually through key delivery decisions and handover.",
  }),
  P("estate-supervision", "houses", "irina", "/images/house.jpg", {
    title: "Авторский надзор частного дома",
    essence: "Присутствие бюро на реализации: скрытые работы, параметры проекта, узкие специалисты. Свожу стороны и веду бюджет, чтобы стройка прошла максимально близко к проекту и смете.",
    who: "Когда важно собрать задуманное, а не удобное. Особенно на доме с несколькими подрядчиками — там легко потерять и характер, и деньги.",
    gets: "Слежение за скрытыми работами и параметрами. Согласованные изменения стоимости. Журнал, фотофиксация, выводы и отчёт.",
    how: "Смотрят разные специалисты бюро, каждый свой контур. Подрядчиков контролируем широко: репутация и реальный опыт. Всех, кому есть дело до объекта, собираю в одном разговоре.",
    why: "Характер и замысел на стройке теряют тихо: узел, замена, спешка, компромисс. Надзор нужен, чтобы замысел и затраты не разъехались.",
    next: "Зависит от этапа. Обычно до сдачи ключевых решений и ввода в эксплуатацию.",
  }, {
    title: "Author’s supervision of a private house",
    essence: "The bureau present on delivery: hidden work, project parameters, specialists. I bring the parties together and hold the budget so the site stays close to the project and the estimate.",
    who: "When what was intended must be built, not what is convenient. Especially with several contractors — character and money are easy to lose.",
    gets: "Watch on hidden work and parameters. Agreed cost changes. A log, photographs, findings and a report.",
    how: "Different specialists of the bureau, each their contour. Contractors read widely: reputation and actual work. Everyone with a stake in one conversation.",
    why: "Character is lost quietly on site: a junction, a substitution, haste, a compromise. Supervision keeps idea and cost from drifting apart.",
    next: "It depends on the stage. Usually through key handover and commissioning.",
  }),
  P("temple", "temples", "irina", "/images/chapel.jpg", {
    title: "Храмовая архитектура",
    essence: "Храм как место и конструкция. Сдержанность в теме, которую легко перегрузить цитатой.",
    who: "Приходы, епархии и частные заказчики священных объёмов — когда нужна точность света и конструкции, а не декоративный купол «по образцу».",
    gets: "Пока — зарезервированный раздел. Авторский контент появится; сейчас демо-кадр и рамка страницы.",
    how: "Работа с каноном, конструкцией и местом. Без шума.",
    why: "Священное не нуждается в лишнем жесте. Нужна точность просвета.",
    next: "Напишите, если есть задача. Тексты и фото заменим на авторские.",
  }, {
    title: "Sacred architecture",
    essence: "Temple as place and structure. Restraint in a brief that is easy to overload.",
    who: "Parishes and private clients of sacred volumes who need light and construction, not a quoted dome.",
    gets: "A reserved section. Author’s content will replace the demo frame.",
    how: "Canon, structure, place. Without noise.",
    why: "The sacred does not need an extra gesture. It needs a precise slit of light.",
    next: "Write if there is a brief. Texts and photographs will be replaced.",
  }, true),
];

export const bureauProducts: Product[] = [
  P("analysis", "pre", "bureau", "/images/bureau.jpg", {
    title: "Предпроектный анализ",
    essence: "Системная проверка исходных данных, ограничений и рисков до начала проектирования.",
    who: "Собственники, инвесторы и девелоперы на входе в проект или с участком, в возможностях которого ещё нет уверенности.",
    gets: "Картину: что можно реализовать, где жёсткие ограничения, где риски согласований. Дорожную карту дальнейших действий.",
    how: "Собираем и проверяем исходные данные. Анализируем градостроительные, технические и экономические ограничения. Оцениваем риски экспертизы.",
    why: "Большинство проблем рождаются не на чертежах, а раньше — из-за неполного понимания задачи.",
    next: "Аналитический отчёт, обычно от одной до трёх недель. Затем ТЗ, эскиз или корректировка самой задачи.",
  }, {
    title: "Pre-design analysis",
    essence: "A systematic check of data, limits and risks before design starts.",
    who: "Owners, investors and developers entering a project or holding land they do not yet trust.",
    gets: "What can be built, what is hard, where approvals will catch. A map of next moves.",
    how: "We gather data, read planning, technical and economic limits, and score review risk.",
    why: "Most failures are born before drawings — in a thin reading of the task.",
    next: "A report, usually one to three weeks. Then a brief, a sketch, or a change of the task itself.",
  }),
  P("brief", "pre", "bureau", "/images/bureau.jpg", {
    title: "Разработка ТЗ",
    essence: "Документ, который фиксирует требования к объекту и задаёт рамки всей проектной работы. Точный для проектировщиков и понятный заказчику. Универсальный: с ним можно идти и в другое бюро.",
    who: "Когда основные параметры ясны и нужно избежать потом взаимных претензий «мы имели в виду другое».",
    gets: "Требования к архитектуре, функционалу, технике, срокам и результату. Основу договора и инструмент контроля.",
    how: "Уточняем цели. Структурируем требования. Проверяем реализуемость. Формулируем ТЗ в рабочей, а не формальной логике.",
    why: "Плохое ТЗ — частая причина срыва сроков, роста стоимости и разочарований.",
    next: "Согласованное ТЗ, от нескольких дней до двух недель. Затем эскиз или стадия П.",
  }, {
    title: "Design brief (TZ)",
    essence: "The document that sets requirements and frames all design work. Precise for designers, clear for the client, and portable to another bureau.",
    who: "When the main parameters are known and you want to avoid “we meant something else”.",
    gets: "Requirements for architecture, use, technique, time and result. A contract base and a control tool.",
    how: "Aims, structure, feasibility, a working brief — not a formal one.",
    why: "A bad brief is a common cause of delay, cost and disappointment.",
    next: "An agreed brief, days to two weeks. Then a sketch or stage P.",
  }),
  P("sketch", "pre", "bureau", "/images/mansion.jpg", {
    title: "Эскизная концепция",
    essence: "Быстрая проверка архитектурной идеи до тяжёлой проектной машины. Эскизируем свободно, консультация на входе — открытая.",
    who: "На старте или когда образ и планировочная логика ещё не зафиксированы.",
    gets: "Несколько рабочих вариантов с плюсами и ограничениями. Возможность отбросить лишнее до стадии П.",
    how: "Обсуждаем задачу. Эскизируем без жёстких рамок «как принято». Проверяем на участок, нормы и логику использования.",
    why: "На ранней стадии дешевле проверить гипотезы, чем потом переделывать проект.",
    next: "Набор эскизов и логика выбранного решения. Затем ОПР, АГО или стадия П.",
  }, {
    title: "Sketch concept",
    essence: "A fast test of an architectural idea before the heavy machine. The first consultation is open.",
    who: "At the start, or when image and plan logic are not yet fixed.",
    gets: "Working options with pluses and limits. A chance to drop the weak before stage P.",
    how: "Talk, sketch without habit, check against site, code and use.",
    why: "Hypotheses are cheap early and expensive later.",
    next: "Sketches and a chosen logic. Then spatial design, AGO or stage P.",
  }),
  P("ago", "pre", "bureau", "/images/mansion.jpg", {
    title: "АГО — комплект под градсовет",
    essence: "Документ облика, подготовленный по стандартам градсовета и территории. Можем согласовать со заинтересованными сторонами.",
    who: "Проекты, где внешний вид проходит органы архитектуры. Особенно в зонах с особыми требованиями.",
    gets: "Комплект в требуемом формате. Документ, с которым можно выходить на согласование.",
    how: "Изучаем требования территории и градсовета. Собираем решение, которое работает архитектурно и проходит по регламентам. При необходимости сопровождаем согласование.",
    why: "АГО — точка, где проект спокойно двигается или надолго застревает.",
    next: "Комплект АГО. Затем стадия П или объёмно-планировочные решения.",
  }, {
    title: "AGO — pack for the planning board",
    essence: "An appearance document to the board’s standard. We can walk it through the parties.",
    who: "Projects whose look must pass architecture authorities.",
    gets: "A pack in the required form, ready to take in.",
    how: "Territory and board requirements. A solution that is architecture and regulation. Accompaniment if needed.",
    why: "AGO is where a project moves — or stalls.",
    next: "The pack. Then stage P or spatial design.",
  }),
  P("spatial", "pre", "bureau", "/images/house.jpg", {
    title: "Объёмно-планировочные решения",
    essence: "Архитектура начинает работать с экономикой, нормативами и логикой использования. Связываем желаемый результат с тем, что можно построить и эксплуатировать.",
    who: "Когда концепция есть, но ещё не зафиксированы планировки, объёмы и ТЭП.",
    gets: "Проработанные планировки и объёмы, увязанные с нормами, технологией и экономикой. Понятные технико-экономические показатели.",
    how: "Берём концепцию и АГО. Проверяем нормативную и технологическую базу. Связываем архитектуру с экономикой и потребительским опытом.",
    why: "Именно здесь идея становится рабочим основанием для проектирования.",
    next: "Комплект ОПР с ТЭП. Обычно далее — стадия П.",
  }, {
    title: "Spatial and planning design",
    essence: "Architecture meeting economy, code and use. Desire bound to what can actually be built and run.",
    who: "When a concept exists but plans, volumes and metrics are not fixed.",
    gets: "Worked plans and volumes, tied to code, technique and money. Clear metrics.",
    how: "From concept and AGO. Code, technique, economy and user experience in one.",
    why: "This is where an idea becomes a basis for design.",
    next: "A spatial pack with metrics. Usually then stage P.",
  }),
  P("stage-p", "design", "bureau", "/images/bureau.jpg", {
    title: "Проектная документация — стадия П",
    essence: "Комплект, который определяет архитектурные, конструктивные и инженерные решения и служит основой для экспертизы. Все разделы — как единая система.",
    who: "Заказчики, готовые переходить от концепции к разрешению на строительство. Новое строительство и реконструкция.",
    gets: "Полный комплект, в котором решения закрывают задачу и оставляют возможность развития объекта. Чтение контекста места и культурного кода заказчика.",
    how: "Уточняем данные, концепцию и ТЗ, формируем дорожную карту. Разделы ведутся взаимосвязанно. Заранее закладываем решения, которые помогают пройти экспертизу.",
    why: "Проектируем не для галочки. По нашим проектам не было отказов в положительном заключении экспертизы.",
    next: "Комплект к экспертизе. После заключения — стадия Р.",
  }, {
    title: "Design documentation — stage P",
    essence: "The pack that sets architecture, structure and engineering and goes to expert review. All sections as one system.",
    who: "Clients ready to move from concept to a building permit. New work and reconstruction.",
    gets: "A full pack that solves the task and leaves room for the object to grow. A reading of place and of the client’s cultural code.",
    how: "Data, concept, brief, a roadmap. Sections in concert. Decisions laid in to pass review.",
    why: "We do not design for a tick. Our projects have not been refused a positive expert review.",
    next: "The pack for review. Then stage R.",
  }),
  P("stage-r", "design", "bureau", "/images/bureau.jpg", {
    title: "Рабочая документация — стадия Р",
    essence: "Детализированный комплект, по которому объект строится. Инженерия поддерживает архитектуру и раскрывает замысел. Каждое решение — расчётом, без перезаклада.",
    who: "Когда стадия П утверждена и объект идёт на площадку. Особенно на сложных и нестандартных конструкциях.",
    gets: "Рабочий комплект со спецификациями, технологическими описаниями и цифровыми моделями против коллизий. Чек-лист контроля для заказчика — в зоне его ответственности, не замена технадзору.",
    how: "Широкая палитра инженерных возможностей. Логика реальной последовательности работ. Педантичность исполнения.",
    why: "От качества РД зависит, насколько спокойно замысел будет воплощён на площадке.",
    next: "Комплект подрядчику. Затем авторский надзор и сопровождение строительства.",
  }, {
    title: "Working documentation — stage R",
    essence: "The detailed pack the site is built from. Engineering serving architecture. Every decision calculated, without fat.",
    who: "When stage P is approved and the object goes to site. Especially on difficult structure.",
    gets: "A working set, specifications, method notes, digital models against clashes. A client checklist — not a substitute for site supervision.",
    how: "A wide engineering palette. Real construction sequence. Pedantry of execution.",
    why: "The calm of the site depends on the quality of stage R.",
    next: "The pack to the contractor. Then author’s supervision and construction support.",
  }),
  P("survey", "service", "bureau", "/images/lab.jpg", {
    title: "Обследование зданий и технический аудит",
    essence: "Проверка фактического состояния конструкций и систем с расчётным обоснованием по ГОСТ и СП, с современным оборудованием.",
    who: "Собственники и инвесторы перед реконструкцией, капремонтом, сменой функционала или просто для понимания реального состояния.",
    gets: "Полноценный отчёт, достаточный для стратегических решений без риска ошибок.",
    how: "Обследуем по нормам. Фиксируем основание для решений, а не формальное заключение.",
    why: "Без точной картины состояния дальше проектируют вслепую.",
    next: "Отчёт. Затем реконструкция, усиление, смена функции или отказ от лишнего.",
  }, {
    title: "Building survey and technical audit",
    essence: "The actual state of structure and systems, calculated to code, with proper equipment.",
    who: "Owners and investors before reconstruction, major repair, a change of use, or simply to know.",
    gets: "A full report that can carry a strategic decision.",
    how: "Survey to the norms. A basis for decisions, not a formal stamp.",
    why: "Without a true picture, design continues blind.",
    next: "A report. Then reconstruction, strengthening, a change of use — or stopping the waste.",
  }),
  P("feasibility", "service", "bureau", "/images/bureau.jpg", {
    title: "ТЭО — подбор и комплектация",
    essence: "Моделирование технико-экономических показателей, реальные рыночные цены, предварительная смета и пул поставщиков.",
    who: "Когда нужно понять стоимость и комплектацию до закупки и стройки — на этапе согласования концепции и дальше.",
    gets: "Декомпозицию проекта на материалы и цены. Обоснование устойчивых технических и экономических решений. Ведомости и сметную логику.",
    how: "Фиксируем ТЭП. Подбираем решения по стоимости, технике и эстетике. Считаем предварительную смету. При необходимости ведём переговоры с подрядчиками.",
    why: "Без ранней ясности в деньгах архитектура быстро становится необязательной.",
    next: "Расчёт с вариантами комплектации. Затем уточнение концепции, проектирование или корректировка финансовой модели.",
  }, {
    title: "Feasibility, specification and costing",
    essence: "Metrics, real market prices, a first estimate and a pool of suppliers.",
    who: "When cost and specification must be seen before purchase and site.",
    gets: "The project broken into materials and prices. Stable technical and economic choices. Bills and estimate logic.",
    how: "We fix metrics, pick by cost, technique and look, draft an estimate, talk to contractors if needed.",
    why: "Without early money-clarity, architecture becomes optional.",
    next: "A calculation with specification options. Then concept, design or a change of the financial model.",
  }),
  P("consulting", "service", "bureau", "/images/bureau.jpg", {
    title: "Архитектурно-строительный консалтинг",
    essence: "Навигация по проектированию, согласованиям и реализации. Ясность на старте и проверка уже существующей документации.",
    who: "Заказчики, которые хотят снизить риски до полноценного проектирования или проверить имеющиеся материалы.",
    gets: "Дорожную карту, понимание стоимостей проектных услуг и требований по согласованиям. При необходимости — глубокий аудит документации с правовой, инженерной и финансовой стороны.",
    how: "Предпроектный аудит исходных данных. Разбираем, что есть, чего не хватает. Документацию проверяем многоступенчато.",
    why: "Ошибки на входе часто дороже самого консалтинга.",
    next: "Выводы, карта и рекомендации. Затем проектирование, доработка или иной рациональный шаг.",
  }, {
    title: "Architecture and construction consulting",
    essence: "Navigation through design, approvals and delivery. Clarity at the start, and a check of documents you already hold.",
    who: "Clients who want less risk before full design, or a reading of existing materials.",
    gets: "A roadmap, a sense of design costs and approval requirements. A deep legal, engineering and financial audit if needed.",
    how: "A pre-design audit of data. What exists, what is missing. Documents checked in layers.",
    why: "Mistakes at the entrance often cost more than the consulting.",
    next: "Findings and a map. Then design, revision, or another rational step.",
  }),
  P("cm", "build", "bureau", "/images/bureau.jpg", {
    title: "Комплексное управление строительством",
    essence: "Сопровождение реализации: диалог с подрядчиками, проверка смет и комплектации, управляемость площадки — не формальный надзор.",
    who: "Заказчики, которые хотят снизить хаос при передаче проекта подрядчику и дальше по ходу строительства.",
    gets: "Помощь в подборе подрядчиков, проверку смет, понятные объёмы по ведомостям, варианты проверенных производителей.",
    how: "Участвуем на передаче ПСД. Переводим решения на язык стройки. Контролируем, чтобы закупки соответствовали проекту.",
    why: "Проблемы чаще начинаются не из-за чертежей, а из-за разрыва между проектом и реализацией.",
    next: "От точечного участия до плотного сопровождения. Обычно вместе с авторским надзором и функцией техзаказчика.",
  }, {
    title: "Construction management",
    essence: "Delivery support: talk with contractors, estimates, specification, a manageable site — not a formal watch.",
    who: "Clients who want less chaos when the pack meets the contractor.",
    gets: "Help choosing contractors, estimate checks, quantities from the bills, proven makers.",
    how: "We join the handover, translate design into site language, keep purchases to the project.",
    why: "Trouble starts in the gap between project and delivery, not in the drawings.",
    next: "From light presence to dense support. Often with author’s supervision and the employer’s agent role.",
  }),
  P("client", "build", "bureau", "/images/bureau.jpg", {
    title: "Функция технического заказчика",
    essence: "Сопровождение интересов заказчика: ИРД, задания подрядчикам, согласования вплоть до ввода. Организационная и нормативная нагрузка — на нас.",
    who: "Кто не хочет самостоятельно погружаться в получение исходных данных, ТЗ подрядчикам и многочисленные согласования.",
    gets: "ИРД без «переполучения» условий. Релевантные коммерческие предложения. Сопровождение инстанций до ввода в эксплуатацию.",
    how: "Собираем данные, опираясь на опыт подачи заявок. Формируем задания. Ведём коммуникацию с органами, ресурсоснабжением и экспертизой.",
    why: "Проекты теряют время на организационных этапах — неполные данные, некорректные задания, затянутые согласования.",
    next: "Подключение с любого этапа — от ИРД до ввода. Часто с надзором и управлением строительством.",
  }, {
    title: "Employer’s agent",
    essence: "The client’s side: baseline data, contractor briefs, consents through to handover. Organisation and regulation on us.",
    who: "Anyone who does not want to live inside applications, contractor briefs and a chain of authorities.",
    gets: "Baseline data without re-applying conditions. Relevant bids. Consents through to commissioning.",
    how: "We gather data, write briefs, talk to authorities, utilities and review.",
    why: "Projects lose time on organisation — thin data, bad briefs, slow consents.",
    next: "Join at any stage, from baseline data to handover. Often with supervision and construction management.",
  }),
  P("supervision", "build", "bureau", "/images/mansion.jpg", {
    title: "Авторский надзор",
    essence: "Сопровождение строительства авторами проекта: технико-технологическое и идеологическое. Точность исполнения и сохранность замысла.",
    who: "Кому важно, чтобы объект был построен по проекту, а не «как получилось». Особенно на сложных объектах.",
    gets: "Контроль скрытых работ и несущих конструкций, фиксацию соответствия, помощь в материалах, участие в рабочих группах.",
    how: "Проверяем площадку поэтапно. Согласовываем изменения и вносим их в исполнительную документацию. Подключаемся к комплектации и графику.",
    why: "Даже сильный проект теряет качество из-за человеческого фактора и накопления мелких отклонений.",
    next: "Плотность зависит от объекта. Часто совмещается с техзаказчиком и управлением строительством.",
  }, {
    title: "Author’s supervision",
    essence: "The authors on site: technical and ideological. Accuracy of building, and the idea kept.",
    who: "Anyone who needs the object built as designed, not “as it came out”. Especially on difficult work.",
    gets: "Checks of hidden work and structure, a record of conformity, help with materials, presence in working groups.",
    how: "We check the site in stages, agree changes into as-built documents, join specification and programme.",
    why: "Even a strong project loses quality to small deviations.",
    next: "Density follows the object. Often with the employer’s agent role and construction management.",
  }),
  P("brand", "business", "bureau", "/images/resort.jpg", {
    title: "Бренд-стратегия: аудит и разработка",
    essence: "Позиционирование и смысловая платформа продукта или объекта. Связанная система, в которой возможности бизнеса встречаются с рынком.",
    who: "Предприниматели, запускающие или обновляющие проект, которым нужно не «название и стиль», а логика, работающая на продажи и повторный спрос.",
    gets: "Целостную платформу: позиционирование, смыслы и опыт. Результат, который можно сразу использовать.",
    how: "Аудит, если есть что аудировать. Исследуем возможности и ожидания рынка. Собираем систему, а не разрозненные элементы.",
    why: "Размытое позиционирование дорого обходится в продажах и коммуникациях.",
    next: "Стратегический документ. Затем коммуникационная стратегия или запуск конкретных задач.",
  }, {
    title: "Brand strategy: audit and development",
    essence: "Positioning and a meaning platform. Business capacity meeting the market as one system.",
    who: "Founders launching or renewing a project who need logic for sales and return demand — not a name and a style.",
    gets: "A whole platform: position, meanings, experience. Usable at once.",
    how: "Audit if there is something to audit. Market, capacity, a system instead of loose pieces.",
    why: "A vague position is expensive in sales and in talk.",
    next: "A strategy document. Then communications or specific launch tasks.",
  }),
  P("finance", "business", "bureau", "/images/bureau.jpg", {
    title: "Финансово-экономическое моделирование",
    essence: "Расчёт проекта в деньгах с разными сценариями. Реальная доходность, а не один «красивый» прогноз.",
    who: "Инвесторы и собственники, которым важно увидеть экономику до серьёзных вложений.",
    gets: "Прозрачную модель с вариантами развития, точками риска и условиями жизнеспособности.",
    how: "Собираем допущения. Считаем несколько сценариев. Не сглаживаем цифры ради комфорта.",
    why: "Красивая архитектура без рабочей экономики быстро перестаёт радовать.",
    next: "Модель с пояснениями. Затем уточнение концепции, параметров объекта или решение об инвестировании.",
  }, {
    title: "Financial modelling",
    essence: "The project in money, with scenarios. Real yield, not one pretty forecast.",
    who: "Investors and owners who need the economy before serious spend.",
    gets: "A transparent model: paths, risk points, conditions of life.",
    how: "Assumptions, several scenarios, no smoothing for comfort.",
    why: "Fine architecture without a working economy stops pleasing quickly.",
    next: "A model with notes. Then a change of concept, of parameters, or a decision to invest.",
  }),
  P("comms", "business", "bureau", "/images/resort.jpg", {
    title: "Коммуникационная стратегия",
    essence: "Система целей, сообщений, каналов и способов измерения. Коммуникации растут из сути проекта и бренда, а не живут отдельно.",
    who: "Предприниматели, которым нужна управляемость интереса к проекту — на старте или когда активности уже есть, но нет общей логики.",
    gets: "Рамку: что говорить, кому, через какие каналы и как понимать, что это работает.",
    how: "Аудит коммуникаций, если они есть. Собираем цели, сообщения и логику каналов. При необходимости сопровождаем исполнение.",
    why: "Разрозненные коммуникации быстро теряют силу и бюджет.",
    next: "Стратегия с планом действий. Затем последовательное исполнение, а не разовые акции.",
  }, {
    title: "Communications strategy",
    essence: "Aims, messages, channels and measures as one system, grown from the project and the brand.",
    who: "Founders who need to govern interest — at the start, or when activity exists without a common logic.",
    gets: "A frame: what to say, to whom, through which channels, and how to know it works.",
    how: "An audit if there is talk already. Aims, messages, channel logic. Delivery if needed.",
    why: "Loose communications lose force and budget quickly.",
    next: "A strategy and a plan. Then sequence, not one-off acts.",
  }),
];

export function productsOf(site: "irina" | "bureau", group?: string) {
  const list = site === "irina" ? irinaProducts : bureauProducts;
  return group ? list.filter((p) => p.group === group) : list;
}

export function findProduct(site: "irina" | "bureau", slug: string) {
  return (site === "irina" ? irinaProducts : bureauProducts).find((p) => p.slug === slug);
}

export const productLabels: Record<Lang, Record<string, string>> = {
  ru: {
    essence: "Суть",
    who: "Для кого и когда",
    gets: "Что получает клиент",
    how: "Как работаем",
    why: "Почему это важно",
    next: "Формат и следующий шаг",
    cta: "Написать",
    demo: "Раздел в работе — демо",
    all: "Все услуги",
  },
  en: {
    essence: "Essence",
    who: "For whom, and when",
    gets: "What you receive",
    how: "How we work",
    why: "Why it matters",
    next: "Format and next step",
    cta: "Write",
    demo: "In progress — demo",
    all: "All services",
  },
};
