"use client";
import { sitePath } from "@/lib/site-path";

import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
export function ContactForm(){
 const [topic,setTopic]=useState(""); const [draft,setDraft]=useState<{href:string,text:string}|null>(null); const [copied,setCopied]=useState(false);
 useEffect(()=>{setTopic(new URLSearchParams(window.location.search).get("topic")??"");},[]);
 return <form className="contact-form" onChange={()=>{setDraft(null);setCopied(false);}} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const subject=topic||"Новый архитектурный проект";const body=`Здравствуйте!\n\n${data.get("message")}\n\n${data.get("name")}\n${data.get("email")}`;setDraft({href:`mailto:hello@im-architect.ru?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,text:`Тема: ${subject}\n\n${body}`});}}><p className="section-label">Расскажите о вашей задаче</p><div className="form-row"><label htmlFor="contact-name">Ваше имя<Input id="contact-name" className="form-input" name="name" autoComplete="name" placeholder="Как к вам обращаться" required maxLength={100}/></label><label htmlFor="contact-email">Электронная почта<Input id="contact-email" className="form-input" name="email" type="email" autoComplete="email" placeholder="name@example.ru" required maxLength={200}/></label></div><label htmlFor="contact-topic">Тема<Input id="contact-topic" name="topic" className="form-input" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Дом, территория, консультация…" maxLength={160}/></label><label htmlFor="contact-message">О проекте<Textarea className="form-input" id="contact-message" name="message" placeholder="Что вы хотите создать? Где находится участок и на каком этапе проект?" required minLength={10} maxLength={5000} rows={5}/></label><div className="form-actions"><Button type="submit" className="solid-button">Подготовить письмо</Button><p>Подготовим письмо для вашей почтовой программы. Вы сможете проверить его перед отправкой.</p></div>{draft&&<div className="draft-result" role="status"><h3>Письмо подготовлено</h3><p>Откройте его в почтовой программе и отправьте на hello@im-architect.ru.</p><div><a className="text-link" href={sitePath(draft.href)}>Открыть письмо</a><Button type="button" className="copy-button" onClick={async()=>{try{await navigator.clipboard.writeText(draft.text);setCopied(true);}catch{setCopied(false);}}}>{copied?"Текст скопирован":"Скопировать текст"}</Button></div></div>}</form>;
}
