/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as BureauIndexRouteImport } from './routes/bureau/index'
import { Route as BureauKontaktRouteImport } from './routes/bureau/kontakt'
import { Route as BureauNovostiRouteImport } from './routes/bureau/novosti'
import { Route as BureauProektyRouteImport } from './routes/bureau/proekty'
import { Route as BureauRabotyRouteImport } from './routes/bureau/raboty'
import { Route as BureauStadiiRouteImport } from './routes/bureau/stadii'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as NapravleniyaIndexRouteImport } from './routes/napravleniya/index'
import { Route as NapravleniyaSlugRouteImport } from './routes/napravleniya/$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as BureauProektyIndexRouteImport } from './routes/bureau/proekty.index'
import { Route as BureauProektySlugRouteImport } from './routes/bureau/proekty.$slug'
import { Route as BureauRabotyIndexRouteImport } from './routes/bureau/raboty.index'
import { Route as BureauRabotySlugRouteImport } from './routes/bureau/raboty.$slug'
import { Route as BureauStadiiIndexRouteImport } from './routes/bureau/stadii.index'
import { Route as BureauStadiiSlugRouteImport } from './routes/bureau/stadii.$slug'
import { Route as NapravleniyaSlugIndexRouteImport } from './routes/napravleniya/$slug.index'
import { Route as NapravleniyaSlugProductRouteImport } from './routes/napravleniya/$slug.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauIndexRoute = BureauIndexRouteImport.update({
  id: '/bureau/',
  path: '/bureau/',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauKontaktRoute = BureauKontaktRouteImport.update({
  id: '/bureau/kontakt',
  path: '/bureau/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauNovostiRoute = BureauNovostiRouteImport.update({
  id: '/bureau/novosti',
  path: '/bureau/novosti',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauProektyRoute = BureauProektyRouteImport.update({
  id: '/bureau/proekty',
  path: '/bureau/proekty',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauRabotyRoute = BureauRabotyRouteImport.update({
  id: '/bureau/raboty',
  path: '/bureau/raboty',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauStadiiRoute = BureauStadiiRouteImport.update({
  id: '/bureau/stadii',
  path: '/bureau/stadii',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaIndexRoute = NapravleniyaIndexRouteImport.update({
  id: '/napravleniya/',
  path: '/napravleniya/',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaSlugRoute = NapravleniyaSlugRouteImport.update({
  id: '/napravleniya/$slug',
  path: '/napravleniya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauProektyIndexRoute = BureauProektyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BureauProektyRoute,
} as any)
const BureauProektySlugRoute = BureauProektySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BureauProektyRoute,
} as any)
const BureauRabotyIndexRoute = BureauRabotyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BureauRabotyRoute,
} as any)
const BureauRabotySlugRoute = BureauRabotySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BureauRabotyRoute,
} as any)
const BureauStadiiIndexRoute = BureauStadiiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BureauStadiiRoute,
} as any)
const BureauStadiiSlugRoute = BureauStadiiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BureauStadiiRoute,
} as any)
const NapravleniyaSlugIndexRoute = NapravleniyaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NapravleniyaSlugRoute,
} as any)
const NapravleniyaSlugProductRoute = NapravleniyaSlugProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => NapravleniyaSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/bureau/kontakt': typeof BureauKontaktRoute
  '/bureau/novosti': typeof BureauNovostiRoute
  '/bureau/proekty': typeof BureauProektyRouteWithChildren
  '/bureau/raboty': typeof BureauRabotyRouteWithChildren
  '/bureau/stadii': typeof BureauStadiiRouteWithChildren
  '/napravleniya/$slug': typeof NapravleniyaSlugRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/bureau/': typeof BureauIndexRoute
  '/lab/': typeof LabIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/bureau/proekty/$slug': typeof BureauProektySlugRoute
  '/bureau/raboty/$slug': typeof BureauRabotySlugRoute
  '/bureau/stadii/$slug': typeof BureauStadiiSlugRoute
  '/napravleniya/$slug/$product': typeof NapravleniyaSlugProductRoute
  '/bureau/proekty/': typeof BureauProektyIndexRoute
  '/bureau/raboty/': typeof BureauRabotyIndexRoute
  '/bureau/stadii/': typeof BureauStadiiIndexRoute
  '/napravleniya/$slug/': typeof NapravleniyaSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/bureau/kontakt': typeof BureauKontaktRoute
  '/bureau/novosti': typeof BureauNovostiRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/bureau': typeof BureauIndexRoute
  '/lab': typeof LabIndexRoute
  '/napravleniya': typeof NapravleniyaIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/bureau/proekty/$slug': typeof BureauProektySlugRoute
  '/bureau/raboty/$slug': typeof BureauRabotySlugRoute
  '/bureau/stadii/$slug': typeof BureauStadiiSlugRoute
  '/napravleniya/$slug/$product': typeof NapravleniyaSlugProductRoute
  '/bureau/proekty': typeof BureauProektyIndexRoute
  '/bureau/raboty': typeof BureauRabotyIndexRoute
  '/bureau/stadii': typeof BureauStadiiIndexRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/bureau/kontakt': typeof BureauKontaktRoute
  '/bureau/novosti': typeof BureauNovostiRoute
  '/bureau/proekty': typeof BureauProektyRouteWithChildren
  '/bureau/raboty': typeof BureauRabotyRouteWithChildren
  '/bureau/stadii': typeof BureauStadiiRouteWithChildren
  '/napravleniya/$slug': typeof NapravleniyaSlugRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/bureau/': typeof BureauIndexRoute
  '/lab/': typeof LabIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/bureau/proekty/$slug': typeof BureauProektySlugRoute
  '/bureau/raboty/$slug': typeof BureauRabotySlugRoute
  '/bureau/stadii/$slug': typeof BureauStadiiSlugRoute
  '/napravleniya/$slug/$product': typeof NapravleniyaSlugProductRoute
  '/bureau/proekty/': typeof BureauProektyIndexRoute
  '/bureau/raboty/': typeof BureauRabotyIndexRoute
  '/bureau/stadii/': typeof BureauStadiiIndexRoute
  '/napravleniya/$slug/': typeof NapravleniyaSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/legal'
    | '/bureau/kontakt'
    | '/bureau/novosti'
    | '/bureau/proekty'
    | '/bureau/raboty'
    | '/bureau/stadii'
    | '/napravleniya/$slug'
    | '/portfolio/$slug'
    | '/bureau/'
    | '/lab/'
    | '/napravleniya/'
    | '/portfolio/'
    | '/bureau/proekty/$slug'
    | '/bureau/raboty/$slug'
    | '/bureau/stadii/$slug'
    | '/napravleniya/$slug/$product'
    | '/bureau/proekty/'
    | '/bureau/raboty/'
    | '/bureau/stadii/'
    | '/napravleniya/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/legal'
    | '/bureau/kontakt'
    | '/bureau/novosti'
    | '/portfolio/$slug'
    | '/bureau'
    | '/lab'
    | '/napravleniya'
    | '/portfolio'
    | '/bureau/proekty/$slug'
    | '/bureau/raboty/$slug'
    | '/bureau/stadii/$slug'
    | '/napravleniya/$slug/$product'
    | '/bureau/proekty'
    | '/bureau/raboty'
    | '/bureau/stadii'
    | '/napravleniya/$slug'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/legal'
    | '/bureau/kontakt'
    | '/bureau/novosti'
    | '/bureau/proekty'
    | '/bureau/raboty'
    | '/bureau/stadii'
    | '/napravleniya/$slug'
    | '/portfolio/$slug'
    | '/bureau/'
    | '/lab/'
    | '/napravleniya/'
    | '/portfolio/'
    | '/bureau/proekty/$slug'
    | '/bureau/raboty/$slug'
    | '/bureau/stadii/$slug'
    | '/napravleniya/$slug/$product'
    | '/bureau/proekty/'
    | '/bureau/raboty/'
    | '/bureau/stadii/'
    | '/napravleniya/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  LegalRoute: typeof LegalRoute
  BureauKontaktRoute: typeof BureauKontaktRoute
  BureauNovostiRoute: typeof BureauNovostiRoute
  BureauProektyRoute: typeof BureauProektyRouteWithChildren
  BureauRabotyRoute: typeof BureauRabotyRouteWithChildren
  BureauStadiiRoute: typeof BureauStadiiRouteWithChildren
  NapravleniyaSlugRoute: typeof NapravleniyaSlugRouteWithChildren
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  BureauIndexRoute: typeof BureauIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  NapravleniyaIndexRoute: typeof NapravleniyaIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/': {
      id: '/bureau/'
      path: '/bureau'
      fullPath: '/bureau/'
      preLoaderRoute: typeof BureauIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/kontakt': {
      id: '/bureau/kontakt'
      path: '/bureau/kontakt'
      fullPath: '/bureau/kontakt'
      preLoaderRoute: typeof BureauKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/novosti': {
      id: '/bureau/novosti'
      path: '/bureau/novosti'
      fullPath: '/bureau/novosti'
      preLoaderRoute: typeof BureauNovostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/proekty': {
      id: '/bureau/proekty'
      path: '/bureau/proekty'
      fullPath: '/bureau/proekty'
      preLoaderRoute: typeof BureauProektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/raboty': {
      id: '/bureau/raboty'
      path: '/bureau/raboty'
      fullPath: '/bureau/raboty'
      preLoaderRoute: typeof BureauRabotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/stadii': {
      id: '/bureau/stadii'
      path: '/bureau/stadii'
      fullPath: '/bureau/stadii'
      preLoaderRoute: typeof BureauStadiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/': {
      id: '/napravleniya/'
      path: '/napravleniya'
      fullPath: '/napravleniya/'
      preLoaderRoute: typeof NapravleniyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/$slug': {
      id: '/napravleniya/$slug'
      path: '/napravleniya/$slug'
      fullPath: '/napravleniya/$slug'
      preLoaderRoute: typeof NapravleniyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau/proekty/': {
      id: '/bureau/proekty/'
      path: '/'
      fullPath: '/bureau/proekty/'
      preLoaderRoute: typeof BureauProektyIndexRouteImport
      parentRoute: typeof BureauProektyRoute
    }
    '/bureau/proekty/$slug': {
      id: '/bureau/proekty/$slug'
      path: '/$slug'
      fullPath: '/bureau/proekty/$slug'
      preLoaderRoute: typeof BureauProektySlugRouteImport
      parentRoute: typeof BureauProektyRoute
    }
    '/bureau/raboty/': {
      id: '/bureau/raboty/'
      path: '/'
      fullPath: '/bureau/raboty/'
      preLoaderRoute: typeof BureauRabotyIndexRouteImport
      parentRoute: typeof BureauRabotyRoute
    }
    '/bureau/raboty/$slug': {
      id: '/bureau/raboty/$slug'
      path: '/$slug'
      fullPath: '/bureau/raboty/$slug'
      preLoaderRoute: typeof BureauRabotySlugRouteImport
      parentRoute: typeof BureauRabotyRoute
    }
    '/bureau/stadii/': {
      id: '/bureau/stadii/'
      path: '/'
      fullPath: '/bureau/stadii/'
      preLoaderRoute: typeof BureauStadiiIndexRouteImport
      parentRoute: typeof BureauStadiiRoute
    }
    '/bureau/stadii/$slug': {
      id: '/bureau/stadii/$slug'
      path: '/$slug'
      fullPath: '/bureau/stadii/$slug'
      preLoaderRoute: typeof BureauStadiiSlugRouteImport
      parentRoute: typeof BureauStadiiRoute
    }
    '/napravleniya/$slug/': {
      id: '/napravleniya/$slug/'
      path: '/'
      fullPath: '/napravleniya/$slug/'
      preLoaderRoute: typeof NapravleniyaSlugIndexRouteImport
      parentRoute: typeof NapravleniyaSlugRoute
    }
    '/napravleniya/$slug/$product': {
      id: '/napravleniya/$slug/$product'
      path: '/$product'
      fullPath: '/napravleniya/$slug/$product'
      preLoaderRoute: typeof NapravleniyaSlugProductRouteImport
      parentRoute: typeof NapravleniyaSlugRoute
    }
  }
}

interface BureauProektyRouteChildren {
  BureauProektySlugRoute: typeof BureauProektySlugRoute
  BureauProektyIndexRoute: typeof BureauProektyIndexRoute
}

const BureauProektyRouteChildren: BureauProektyRouteChildren = {
  BureauProektySlugRoute: BureauProektySlugRoute,
  BureauProektyIndexRoute: BureauProektyIndexRoute,
}

const BureauProektyRouteWithChildren = BureauProektyRoute._addFileChildren(
  BureauProektyRouteChildren,
)

interface BureauRabotyRouteChildren {
  BureauRabotySlugRoute: typeof BureauRabotySlugRoute
  BureauRabotyIndexRoute: typeof BureauRabotyIndexRoute
}

const BureauRabotyRouteChildren: BureauRabotyRouteChildren = {
  BureauRabotySlugRoute: BureauRabotySlugRoute,
  BureauRabotyIndexRoute: BureauRabotyIndexRoute,
}

const BureauRabotyRouteWithChildren = BureauRabotyRoute._addFileChildren(
  BureauRabotyRouteChildren,
)

interface BureauStadiiRouteChildren {
  BureauStadiiSlugRoute: typeof BureauStadiiSlugRoute
  BureauStadiiIndexRoute: typeof BureauStadiiIndexRoute
}

const BureauStadiiRouteChildren: BureauStadiiRouteChildren = {
  BureauStadiiSlugRoute: BureauStadiiSlugRoute,
  BureauStadiiIndexRoute: BureauStadiiIndexRoute,
}

const BureauStadiiRouteWithChildren = BureauStadiiRoute._addFileChildren(
  BureauStadiiRouteChildren,
)

interface NapravleniyaSlugRouteChildren {
  NapravleniyaSlugProductRoute: typeof NapravleniyaSlugProductRoute
  NapravleniyaSlugIndexRoute: typeof NapravleniyaSlugIndexRoute
}

const NapravleniyaSlugRouteChildren: NapravleniyaSlugRouteChildren = {
  NapravleniyaSlugProductRoute: NapravleniyaSlugProductRoute,
  NapravleniyaSlugIndexRoute: NapravleniyaSlugIndexRoute,
}

const NapravleniyaSlugRouteWithChildren =
  NapravleniyaSlugRoute._addFileChildren(NapravleniyaSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  LegalRoute: LegalRoute,
  BureauKontaktRoute: BureauKontaktRoute,
  BureauNovostiRoute: BureauNovostiRoute,
  BureauProektyRoute: BureauProektyRouteWithChildren,
  BureauRabotyRoute: BureauRabotyRouteWithChildren,
  BureauStadiiRoute: BureauStadiiRouteWithChildren,
  NapravleniyaSlugRoute: NapravleniyaSlugRouteWithChildren,
  PortfolioSlugRoute: PortfolioSlugRoute,
  BureauIndexRoute: BureauIndexRoute,
  LabIndexRoute: LabIndexRoute,
  NapravleniyaIndexRoute: NapravleniyaIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
